Add support for Recordings Edl
kodi-pvr/pvr.argustv pull request #143
Opened 2021-12-29 19:45 UTC by rbarthen

ArgusTV PVR has been missing EDL support for recordings since version 17.  I don't normally program C++, but I've been missing the feature enough to try and contribute.  I've borrowed most of the code needed from the pvr.wmc addon to support EDL.  I included the entire Utils Namespace from pvr.wmc, but not all of it is needed for Edl support.  I left the other methods for potential future use.

2021-12-30 13:03 UTC, phunkyfish commented
Thanks for contributing!

The split function is actually available in the binary addon API. You can see an example of it being used in `argustvrpc.cpp`.

So I reckon you can drop the Utils completely, giving you a much shorter PR. Also, please create the PR for Nexus also (that's like master for binary addons). 

Last thing to do then is to increment the middle number in `addon.xml.in` and add an entry to the changelog file.

2021-12-30 13:15 UTC, phunkyfish requested changes
Not sure you need a member variable for `streamFilename`

2021-12-30 13:15 UTC, phunkyfish commented on src/pvrclient-argustv.h
> +  std::string _streamFileName; // the name of the stream file
`m_streamFilename`

Note that case change for the `n` also. But I'm not sure you need a member for this variable. It should be ok to just declare it in the function where it's used. Unless there is another reason to have it as a member?

2021-12-30 13:15 UTC, phunkyfish commented on src/utils.cpp
> +
Likely the changes in this file are no longer needed.

2021-12-30 13:15 UTC, phunkyfish commented on src/utils.cpp
> +
Likely the changes in this file are no longer needed

2021-12-30 13:15 UTC, phunkyfish commented on src/utils.h
> +
Likely the changes in this file are no longer needed

2021-12-30 13:15 UTC, phunkyfish commented on src/utils.h
> +
Likely the changes in this file are no longer needed

2021-12-30 13:15 UTC, phunkyfish commented on src/pvrclient-argustv.cpp
> +  if (!FindRecEntry(recording.GetRecordingId(), _streamFileName))
streamFilename is only used in this function so why not declare it here instead of in the header?

`std::string streamFilename; `

2021-12-30 13:15 UTC, phunkyfish commented on src/pvrclient-argustv.cpp
> +  if (!_streamFileName.empty()) // read the edl for the current stream file
`streamFilename`

2021-12-30 13:15 UTC, phunkyfish commented on src/pvrclient-argustv.cpp
> +    std::string theEdlFile = _streamFileName;
`streamFilename`

2021-12-30 16:36 UTC, phunkyfish requested changes
Please also squash the 3 commits into one.

2021-12-30 16:36 UTC, phunkyfish commented on src/pvrclient-argustv.cpp
> +  std::string m_streamFileName; // the name of the stream file
It’s no longer a member variable so should just be called `streamFilename`

2021-12-30 16:36 UTC, phunkyfish commented on src/pvrclient-argustv.cpp
> +  if (!m_streamFileName.empty()) // read the edl for the current stream file
`streamFilename`

2021-12-30 16:36 UTC, phunkyfish commented on src/pvrclient-argustv.cpp
> +    std::string theEdlFile = m_streamFileName;
`streamFilename`

2021-12-30 17:54 UTC, phunkyfish commented on src/pvrclient-argustv.h
> -
No need to remove this line

2021-12-30 20:18 UTC, rbarthen commented
I'm not sure if I did the squashing correctly.  The updates should have the following corrections:
- minor version updated
- changelog updated
- using addon library for split
- removed utils namespace
- stream file naming corrected
- added back removed line return

2021-12-30 21:02 UTC, phunkyfish requested changes

2021-12-30 21:02 UTC, phunkyfish commented on src/pvrclient-argustv.h
> +
Remove spaces

2021-12-30 21:13 UTC, phunkyfish commented
> I'm not sure if I did the squashing correctly. The updates should have the following corrections:
> 
> * minor version updated
> * changelog updated
> * using addon library for split
> * removed utils namespace
> * stream file naming corrected
> * added back removed line return

Once you have squashed it you should only have a single commit. Then you would force push to your PR branch. What I recommend you do is this.

1. `git checkout -b Matrix-bk` (this will just give you a backup branch in case you need it)
2. `git checkout Matrix` (Switch back to working branch)
3. `git reset HEAD~1` (this will undo your latest commit and put it back to an uncommitted change)
4. Keep running `git reset HEAD~1` until you are back to your origin commit.
5. Once you are back to your original commit (you can check that with `git log --oneline` then:
6. git add -u
7. git commit --amend (this will add all the changes to your original commit)

2021-12-31 06:40 UTC, rbarthen commented
@phunkyfish ,
Apologies for my intermediate knowledge of git. I tried your instructions, but it didn't seem to work because I mistakenly squashed the original PR commit and could not move the HEAD back to it. I checked out that hash for the PR comment, but it resulted in a detached head. I manually merged the latest updates into that detached head and committed with an amend, but it wouldn't push without forcing. I now only see the one commit with a new hash. Hopefully that put things back on track.

2021-12-31 08:36 UTC, phunkyfish commented
> @phunkyfish ,
> Apologies for my intermediate knowledge of git. I tried your instructions, but it didn't seem to work because I mistakenly squashed the original PR commit and could not move the HEAD back to it. I checked out that hash for the PR comment, but it resulted in a detached head. I manually merged the latest updates into that detached head and committed with an amend, but it wouldn't push without forcing. I now only see the one commit with a new hash. Hopefully that put things back on track.

This is correct now. You do need to force push to after squashing as you are overwriting the commit history. Well done for sticking with it!

2021-12-31 08:36 UTC, phunkyfish approved these changes
Thanks for the contribution!,,

2021-12-31 08:41 UTC, phunkyfish commented
Now all you need to do is create a similar PR for the Nexus branch. Nexus is our development branch and everything needs to be merged there first.

All you need to do is cherry-pick the commit (using the hash) over and amend the addon.xml.in and the change log.

2021-12-31 09:04 UTC, phunkyfish commented
@rbarthen the Nexus branch has now been updated so you can create the other PR for there now. I’m not sure how your git repos are setup but if you need any help just ask.

2022-01-01 13:31 UTC, phunkyfish commented
> @rbarthen the Nexus branch has now been updated so you can create the other PR for there now. I’m not sure how your git repos are setup but if you need any help just ask.

@rbarthen I'll create the Nexus PR for you. There is an API change so the Nexus add-on needs to be released anyway and it's very easy to cheery-pick your change over. Thanks again and well done on your first contribution.

2022-01-01 13:32 UTC, merged

2022-01-01 15:57 UTC, rbarthen commented
@phunkyfish ,
Thanks for handling Nexus.  I had started the code change, but got distracted with New Years Eve events.