[cmake] remove usage of kodi-platform
kodi-pvr/pvr.argustv pull request #89
Opened 2019-04-25 19:44 UTC by olafhering

The pvr.argustv binary addon does not use kodi-platform.
Remove existing references from CMakeLists.txt and debian/control.

2019-04-26 08:07 UTC, ksooo commented
@olafhering could you please look at #88 which is basically the same, but slightly different wrt debian handling. Not sure what is correct, though @Rechi

2019-04-26 08:10 UTC, Rechi requested changes
This will break the debian packaging as it now misses p8-platform (was pulled in by libkodiplatform-dev).

2019-04-26 08:13 UTC, ksooo commented
> This will break the debian packaging as it now misses p8-platform (was pulled in by libkodiplatform-dev).

 @olafhering it seems you have to fix all the related PRs you've submitted. :-/

2019-04-26 08:16 UTC, olafhering commented
I will adjust my script and add p8-platform as needed. Thanks for review.

2019-04-26 08:17 UTC, olafhering commented
But before that, the base system has to be fixed to avoid false failures.

2019-04-26 08:19 UTC, Rechi commented
You may also have to add `libtinyxml-dev` (another dependency of libkodiplatform-dev) . But both are not needed for all addons, so only add them where they are needed.

2019-04-30 13:58 UTC, olafhering commented
> You may also have to add `libtinyxml-dev` (another dependency of libkodiplatform-dev) . But both are not needed for all addons, so only add them where they are needed.

Not required for this addon. Not sure how to undo the "Changes requested" thing.

2019-04-30 14:07 UTC, olafhering commented
Doing development outside of master makes contributions cumbersome.
Good luck.

2019-04-30 14:07 UTC, closed without merging